import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface RadicalData {
  num: number;
  radical: string;
  strokes: number;
  pinyin: string;
  definition: string;
}

// All 214 Kangxi radicals
const radicals: RadicalData[] = [
  { num: 1, radical: '一', strokes: 1, pinyin: 'yī', definition: 'one' },
  { num: 2, radical: '丨', strokes: 1, pinyin: 'gǔn', definition: 'line' },
  { num: 3, radical: '丶', strokes: 1, pinyin: 'zhǔ', definition: 'dot' },
  {
    num: 4,
    radical: '丿 (乀乁)',
    strokes: 1,
    pinyin: 'piě',
    definition: 'slash',
  },
  {
    num: 5,
    radical: '乙 (乚乛)',
    strokes: 1,
    pinyin: 'yǐ',
    definition: 'second',
  },
  { num: 6, radical: '亅', strokes: 1, pinyin: 'jué', definition: 'hook' },
  { num: 7, radical: '二', strokes: 2, pinyin: 'ér', definition: 'two' },
  { num: 8, radical: '亠', strokes: 2, pinyin: 'tóu', definition: 'lid' },
  { num: 9, radical: '人 (亻)', strokes: 2, pinyin: 'rén', definition: 'man' },
  { num: 10, radical: '儿', strokes: 2, pinyin: 'rén', definition: 'legs' },
  { num: 11, radical: '入', strokes: 2, pinyin: 'rù', definition: 'enter' },
  {
    num: 12,
    radical: '八 (丷)',
    strokes: 2,
    pinyin: 'bā',
    definition: 'eight',
  },
  {
    num: 13,
    radical: '冂',
    strokes: 2,
    pinyin: 'jiōng',
    definition: 'down box',
  },
  { num: 14, radical: '冖', strokes: 2, pinyin: 'mì', definition: 'cover' },
  { num: 15, radical: '冫', strokes: 2, pinyin: 'bīng', definition: 'ice' },
  { num: 16, radical: '几', strokes: 2, pinyin: 'jǐ', definition: 'table' },
  { num: 17, radical: '凵', strokes: 2, pinyin: 'qū', definition: 'open box' },
  {
    num: 18,
    radical: '刀 (刂)',
    strokes: 2,
    pinyin: 'dāo',
    definition: 'knife',
  },
  { num: 19, radical: '力', strokes: 2, pinyin: 'lì', definition: 'power' },
  { num: 20, radical: '勹', strokes: 2, pinyin: 'bāo', definition: 'wrap' },
  { num: 21, radical: '匕', strokes: 2, pinyin: 'bǐ', definition: 'spoon' },
  {
    num: 22,
    radical: '匚',
    strokes: 2,
    pinyin: 'fāng',
    definition: 'right open box',
  },
  {
    num: 23,
    radical: '匸',
    strokes: 2,
    pinyin: 'xǐ',
    definition: 'hiding enclosure',
  },
  { num: 24, radical: '十', strokes: 2, pinyin: 'shí', definition: 'ten' },
  {
    num: 25,
    radical: '卜',
    strokes: 2,
    pinyin: 'bǔ',
    definition: 'divination',
  },
  {
    num: 26,
    radical: '卩 (㔾)',
    strokes: 2,
    pinyin: 'jié',
    definition: 'seal',
  },
  { num: 27, radical: '厂', strokes: 2, pinyin: 'hǎn', definition: 'cliff' },
  { num: 28, radical: '厶', strokes: 2, pinyin: 'sī', definition: 'private' },
  { num: 29, radical: '又', strokes: 2, pinyin: 'yòu', definition: 'again' },
  { num: 30, radical: '口', strokes: 3, pinyin: 'kǒu', definition: 'mouth' },
  {
    num: 31,
    radical: '囗',
    strokes: 3,
    pinyin: 'wéi',
    definition: 'enclosure',
  },
  { num: 32, radical: '土', strokes: 3, pinyin: 'tǔ', definition: 'earth' },
  { num: 33, radical: '士', strokes: 3, pinyin: 'shì', definition: 'scholar' },
  { num: 34, radical: '夂', strokes: 3, pinyin: 'zhǐ', definition: 'go' },
  {
    num: 35,
    radical: '夊',
    strokes: 3,
    pinyin: 'suī',
    definition: 'go slowly',
  },
  { num: 36, radical: '夕', strokes: 3, pinyin: 'xī', definition: 'evening' },
  { num: 37, radical: '大', strokes: 3, pinyin: 'dà', definition: 'big' },
  { num: 38, radical: '女', strokes: 3, pinyin: 'nǚ', definition: 'woman' },
  { num: 39, radical: '子', strokes: 3, pinyin: 'zǐ', definition: 'child' },
  { num: 40, radical: '宀', strokes: 3, pinyin: 'mián', definition: 'roof' },
  { num: 41, radical: '寸', strokes: 3, pinyin: 'cùn', definition: 'inch' },
  { num: 42, radical: '小', strokes: 3, pinyin: 'xiǎo', definition: 'small' },
  {
    num: 43,
    radical: '尢 (尣)',
    strokes: 3,
    pinyin: 'wāng',
    definition: 'lame',
  },
  { num: 44, radical: '尸', strokes: 3, pinyin: 'shī', definition: 'corpse' },
  { num: 45, radical: '屮', strokes: 3, pinyin: 'chè', definition: 'sprout' },
  {
    num: 46,
    radical: '山',
    strokes: 3,
    pinyin: 'shān',
    definition: 'mountain',
  },
  {
    num: 47,
    radical: '川 (巛巜)',
    strokes: 3,
    pinyin: 'chuān',
    definition: 'river',
  },
  { num: 48, radical: '工', strokes: 3, pinyin: 'gōng', definition: 'work' },
  { num: 49, radical: '己', strokes: 3, pinyin: 'jǐ', definition: 'oneself' },
  { num: 50, radical: '巾', strokes: 3, pinyin: 'jīn', definition: 'turban' },
  { num: 51, radical: '干', strokes: 3, pinyin: 'gān', definition: 'dry' },
  {
    num: 52,
    radical: '幺',
    strokes: 3,
    pinyin: 'yāo',
    definition: 'short thread',
  },
  { num: 53, radical: '广', strokes: 3, pinyin: 'yǎn', definition: 'shelter' },
  {
    num: 54,
    radical: '廴',
    strokes: 3,
    pinyin: 'yǐn',
    definition: 'long stride',
  },
  {
    num: 55,
    radical: '廾',
    strokes: 3,
    pinyin: 'gǒng',
    definition: 'two hands',
  },
  { num: 56, radical: '弋', strokes: 3, pinyin: 'yì', definition: 'shoot' },
  { num: 57, radical: '弓', strokes: 3, pinyin: 'gōng', definition: 'bow' },
  {
    num: 58,
    radical: '彐 (彑)',
    strokes: 3,
    pinyin: 'jì',
    definition: 'snout',
  },
  { num: 59, radical: '彡', strokes: 3, pinyin: 'shān', definition: 'bristle' },
  { num: 60, radical: '彳', strokes: 3, pinyin: 'chì', definition: 'step' },
  {
    num: 61,
    radical: '心 (忄㣺)',
    strokes: 4,
    pinyin: 'xīn',
    definition: 'heart',
  },
  { num: 62, radical: '戈', strokes: 4, pinyin: 'gē', definition: 'spear' },
  {
    num: 63,
    radical: '戶 (户戸)',
    strokes: 4,
    pinyin: 'hù',
    definition: 'door',
  },
  {
    num: 64,
    radical: '手 (扌龵)',
    strokes: 4,
    pinyin: 'shǒu',
    definition: 'hand',
  },
  { num: 65, radical: '支', strokes: 4, pinyin: 'zhī', definition: 'branch' },
  { num: 66, radical: '攴 (攵)', strokes: 4, pinyin: 'pū', definition: 'rap' },
  { num: 67, radical: '文', strokes: 4, pinyin: 'wén', definition: 'script' },
  { num: 68, radical: '斗', strokes: 4, pinyin: 'dǒu', definition: 'dipper' },
  { num: 69, radical: '斤', strokes: 4, pinyin: 'jīn', definition: 'axe' },
  { num: 70, radical: '方', strokes: 4, pinyin: 'fāng', definition: 'square' },
  { num: 71, radical: '无', strokes: 4, pinyin: 'wú', definition: 'without' },
  { num: 72, radical: '日', strokes: 4, pinyin: 'rì', definition: 'sun' },
  { num: 73, radical: '曰', strokes: 4, pinyin: 'yuē', definition: 'say' },
  { num: 74, radical: '月', strokes: 4, pinyin: 'yuè', definition: 'moon' },
  { num: 75, radical: '木', strokes: 4, pinyin: 'mù', definition: 'tree' },
  { num: 76, radical: '欠', strokes: 4, pinyin: 'qiàn', definition: 'owe' },
  { num: 77, radical: '止', strokes: 4, pinyin: 'zhǐ', definition: 'stop' },
  {
    num: 78,
    radical: '歹 (歺)',
    strokes: 4,
    pinyin: 'dǎi',
    definition: 'evil',
  },
  { num: 79, radical: '殳', strokes: 4, pinyin: 'shū', definition: 'weapon' },
  {
    num: 80,
    radical: '毋 (母⺟)',
    strokes: 4,
    pinyin: 'mǔ',
    definition: 'mother',
  },
  { num: 81, radical: '比', strokes: 4, pinyin: 'bǐ', definition: 'compare' },
  { num: 82, radical: '毛', strokes: 4, pinyin: 'máo', definition: 'fur' },
  { num: 83, radical: '氏', strokes: 4, pinyin: 'shì', definition: 'clan' },
  { num: 84, radical: '气', strokes: 4, pinyin: 'qì', definition: 'steam' },
  {
    num: 85,
    radical: '水 (氵氺)',
    strokes: 4,
    pinyin: 'shuǐ',
    definition: 'water',
  },
  {
    num: 86,
    radical: '火 (灬)',
    strokes: 4,
    pinyin: 'huǒ',
    definition: 'fire',
  },
  {
    num: 87,
    radical: '爪 (爫)',
    strokes: 4,
    pinyin: 'zhǎo',
    definition: 'claw',
  },
  { num: 88, radical: '父', strokes: 4, pinyin: 'fù', definition: 'father' },
  { num: 89, radical: '爻', strokes: 4, pinyin: 'yáo', definition: 'line' },
  {
    num: 90,
    radical: '爿 (丬)',
    strokes: 4,
    pinyin: 'qiáng',
    definition: 'piece of wood',
  },
  { num: 91, radical: '片', strokes: 4, pinyin: 'piàn', definition: 'slice' },
  { num: 92, radical: '牙', strokes: 4, pinyin: 'yá', definition: 'tooth' },
  { num: 93, radical: '牛 (牜)', strokes: 4, pinyin: 'niú', definition: 'cow' },
  {
    num: 94,
    radical: '犬 (犭)',
    strokes: 4,
    pinyin: 'quǎn',
    definition: 'dog',
  },
  {
    num: 95,
    radical: '玄',
    strokes: 5,
    pinyin: 'xuán',
    definition: 'profound',
  },
  {
    num: 96,
    radical: '玉 (王⺩)',
    strokes: 5,
    pinyin: 'yù',
    definition: 'jade',
  },
  { num: 97, radical: '瓜', strokes: 5, pinyin: 'guā', definition: 'melon' },
  { num: 98, radical: '瓦', strokes: 5, pinyin: 'wǎ', definition: 'tile' },
  { num: 99, radical: '甘', strokes: 5, pinyin: 'gān', definition: 'sweet' },
  { num: 100, radical: '生', strokes: 5, pinyin: 'shēng', definition: 'life' },
  {
    num: 101,
    radical: '用 (甩)',
    strokes: 5,
    pinyin: 'yòng',
    definition: 'use',
  },
  { num: 102, radical: '田', strokes: 5, pinyin: 'tián', definition: 'field' },
  {
    num: 103,
    radical: '疋 (⺪)',
    strokes: 5,
    pinyin: 'shū',
    definition: 'foot',
  },
  { num: 104, radical: '疒', strokes: 5, pinyin: 'chuáng', definition: 'sick' },
  { num: 105, radical: '癶', strokes: 5, pinyin: 'bō', definition: 'legs' },
  { num: 106, radical: '白', strokes: 5, pinyin: 'bái', definition: 'white' },
  { num: 107, radical: '皮', strokes: 5, pinyin: 'pí', definition: 'skin' },
  { num: 108, radical: '皿', strokes: 5, pinyin: 'mǐn', definition: 'dish' },
  { num: 109, radical: '目', strokes: 5, pinyin: 'mù', definition: 'eye' },
  { num: 110, radical: '矛', strokes: 5, pinyin: 'máo', definition: 'spear' },
  { num: 111, radical: '矢', strokes: 5, pinyin: 'shǐ', definition: 'arrow' },
  { num: 112, radical: '石', strokes: 5, pinyin: 'shí', definition: 'stone' },
  {
    num: 113,
    radical: '示 (礻)',
    strokes: 5,
    pinyin: 'shì',
    definition: 'spirit',
  },
  { num: 114, radical: '禸', strokes: 5, pinyin: 'róu', definition: 'track' },
  { num: 115, radical: '禾', strokes: 5, pinyin: 'hé', definition: 'grain' },
  { num: 116, radical: '穴', strokes: 5, pinyin: 'xué', definition: 'cave' },
  { num: 117, radical: '立', strokes: 5, pinyin: 'lì', definition: 'stand' },
  {
    num: 118,
    radical: '竹 (⺮)',
    strokes: 6,
    pinyin: 'zhú',
    definition: 'bamboo',
  },
  { num: 119, radical: '米', strokes: 6, pinyin: 'mǐ', definition: 'rice' },
  {
    num: 120,
    radical: '糸 (糹纟)',
    strokes: 6,
    pinyin: 'mì',
    definition: 'silk',
  },
  { num: 121, radical: '缶', strokes: 6, pinyin: 'fǒu', definition: 'jar' },
  {
    num: 122,
    radical: '网 (罓罒⺳)',
    strokes: 6,
    pinyin: 'wǎng',
    definition: 'net',
  },
  {
    num: 123,
    radical: '羊 (⺶)',
    strokes: 6,
    pinyin: 'yáng',
    definition: 'sheep',
  },
  { num: 124, radical: '羽', strokes: 6, pinyin: 'yǔ', definition: 'feather' },
  {
    num: 125,
    radical: '老 (耂)',
    strokes: 6,
    pinyin: 'lǎo',
    definition: 'old',
  },
  { num: 126, radical: '而', strokes: 6, pinyin: 'ér', definition: 'and' },
  { num: 127, radical: '耒', strokes: 6, pinyin: 'lěi', definition: 'plough' },
  { num: 128, radical: '耳', strokes: 6, pinyin: 'ěr', definition: 'ear' },
  {
    num: 129,
    radical: '聿 (肀)',
    strokes: 6,
    pinyin: 'yù',
    definition: 'brush',
  },
  {
    num: 130,
    radical: '肉 (月)',
    strokes: 6,
    pinyin: 'ròu',
    definition: 'meat',
  },
  {
    num: 131,
    radical: '臣',
    strokes: 6,
    pinyin: 'chén',
    definition: 'minister',
  },
  { num: 132, radical: '自', strokes: 6, pinyin: 'zì', definition: 'self' },
  { num: 133, radical: '至', strokes: 6, pinyin: 'zhì', definition: 'reach' },
  { num: 134, radical: '臼', strokes: 6, pinyin: 'jiù', definition: 'mortar' },
  { num: 135, radical: '舌', strokes: 6, pinyin: 'shé', definition: 'tongue' },
  {
    num: 136,
    radical: '舛',
    strokes: 6,
    pinyin: 'chuǎn',
    definition: 'oppose',
  },
  { num: 137, radical: '舟', strokes: 6, pinyin: 'zhōu', definition: 'boat' },
  {
    num: 138,
    radical: '艮',
    strokes: 6,
    pinyin: 'gèn',
    definition: 'stop and stare',
  },
  { num: 139, radical: '色', strokes: 6, pinyin: 'sè', definition: 'color' },
  {
    num: 140,
    radical: '艸 (艹)',
    strokes: 6,
    pinyin: 'cǎo',
    definition: 'grass',
  },
  { num: 141, radical: '虍', strokes: 6, pinyin: 'hū', definition: 'tiger' },
  {
    num: 142,
    radical: '虫',
    strokes: 6,
    pinyin: 'chóng',
    definition: 'insect',
  },
  { num: 143, radical: '血', strokes: 6, pinyin: 'xiě', definition: 'blood' },
  { num: 144, radical: '行', strokes: 6, pinyin: 'xíng', definition: 'walk' },
  {
    num: 145,
    radical: '衣 (衤)',
    strokes: 6,
    pinyin: 'yī',
    definition: 'clothing',
  },
  {
    num: 146,
    radical: '西 (襾覀)',
    strokes: 6,
    pinyin: 'xià',
    definition: 'cover',
  },
  {
    num: 147,
    radical: '見 (见)',
    strokes: 7,
    pinyin: 'jiàn',
    definition: 'see',
  },
  { num: 148, radical: '角', strokes: 7, pinyin: 'jué', definition: 'horn' },
  {
    num: 149,
    radical: '言 (訁讠)',
    strokes: 7,
    pinyin: 'yán',
    definition: 'speech',
  },
  { num: 150, radical: '谷', strokes: 7, pinyin: 'gǔ', definition: 'valley' },
  { num: 151, radical: '豆', strokes: 7, pinyin: 'dòu', definition: 'bean' },
  {
    num: 152,
    radical: '豕',
    strokes: 7,
    pinyin: 'shǐ',
    definition: 'a pig, boar',
  },
  {
    num: 153,
    radical: '豸',
    strokes: 7,
    pinyin: 'zhì',
    definition: 'fierce animal',
  },
  {
    num: 154,
    radical: '貝 (贝)',
    strokes: 7,
    pinyin: 'bèi',
    definition: 'shell',
  },
  { num: 155, radical: '赤', strokes: 7, pinyin: 'chì', definition: 'red' },
  {
    num: 156,
    radical: '走 (赱)',
    strokes: 7,
    pinyin: 'zǒu',
    definition: 'run',
  },
  {
    num: 157,
    radical: '足 (⻊)',
    strokes: 7,
    pinyin: 'zú',
    definition: 'foot',
  },
  { num: 158, radical: '身', strokes: 7, pinyin: 'shēn', definition: 'body' },
  {
    num: 159,
    radical: '車 (车)',
    strokes: 7,
    pinyin: 'chē',
    definition: 'cart',
  },
  { num: 160, radical: '辛', strokes: 7, pinyin: 'xīn', definition: 'bitter' },
  {
    num: 161,
    radical: '辰',
    strokes: 7,
    pinyin: 'chén',
    definition: 'morning',
  },
  {
    num: 162,
    radical: '辵 (辶)',
    strokes: 6,
    pinyin: 'chuò',
    definition: 'walk',
  },
  {
    num: 163,
    radical: '邑 (阝)',
    strokes: 7,
    pinyin: 'yì',
    definition: 'city (阝 right)',
  },
  {
    num: 164,
    radical: '酉',
    strokes: 7,
    pinyin: 'yǒu',
    definition: 'wine vessel',
  },
  {
    num: 165,
    radical: '釆',
    strokes: 7,
    pinyin: 'biàn',
    definition: 'discern',
  },
  { num: 166, radical: '里', strokes: 7, pinyin: 'lǐ', definition: 'village' },
  {
    num: 167,
    radical: '金 (釒钅)',
    strokes: 8,
    pinyin: 'jīn',
    definition: 'gold',
  },
  {
    num: 168,
    radical: '長 (长)',
    strokes: 7,
    pinyin: 'cháng',
    definition: 'long',
  },
  {
    num: 169,
    radical: '門 (门)',
    strokes: 8,
    pinyin: 'mén',
    definition: 'gate',
  },
  {
    num: 170,
    radical: '阜 (阝)',
    strokes: 8,
    pinyin: 'fù',
    definition: 'mound, dam (阝 left)',
  },
  { num: 171, radical: '隶', strokes: 8, pinyin: 'dài', definition: 'slave' },
  {
    num: 172,
    radical: '隹',
    strokes: 8,
    pinyin: 'zhuī',
    definition: 'short-tailed bird',
  },
  { num: 173, radical: '雨', strokes: 8, pinyin: 'yǔ', definition: 'rain' },
  {
    num: 174,
    radical: '青 (靑)',
    strokes: 8,
    pinyin: 'qīng',
    definition: 'green',
  },
  { num: 175, radical: '非', strokes: 8, pinyin: 'fēi', definition: 'wrong' },
  {
    num: 176,
    radical: '面 (靣)',
    strokes: 9,
    pinyin: 'miàn',
    definition: 'face',
  },
  { num: 177, radical: '革', strokes: 9, pinyin: 'gé', definition: 'leather' },
  {
    num: 178,
    radical: '韋 (韦)',
    strokes: 9,
    pinyin: 'wéi',
    definition: 'soft leather',
  },
  { num: 179, radical: '韭', strokes: 9, pinyin: 'jiǔ', definition: 'leek' },
  { num: 180, radical: '音', strokes: 9, pinyin: 'yīn', definition: 'sound' },
  {
    num: 181,
    radical: '頁 (页)',
    strokes: 9,
    pinyin: 'yè',
    definition: 'page',
  },
  {
    num: 182,
    radical: '風 (风)',
    strokes: 4,
    pinyin: 'fēng',
    definition: 'wind',
  },
  {
    num: 183,
    radical: '飛 (飞)',
    strokes: 9,
    pinyin: 'fēi',
    definition: 'fly',
  },
  {
    num: 184,
    radical: '食 (飠饣)',
    strokes: 9,
    pinyin: 'shí',
    definition: 'eat',
  },
  { num: 185, radical: '首', strokes: 9, pinyin: 'shǒu', definition: 'head' },
  {
    num: 186,
    radical: '香',
    strokes: 9,
    pinyin: 'xiāng',
    definition: 'fragrant',
  },
  {
    num: 187,
    radical: '馬 (马)',
    strokes: 10,
    pinyin: 'mǎ',
    definition: 'horse',
  },
  { num: 188, radical: '骨', strokes: 10, pinyin: 'gǔ', definition: 'bone' },
  {
    num: 189,
    radical: '高 (髙)',
    strokes: 10,
    pinyin: 'gāo',
    definition: 'tall',
  },
  { num: 190, radical: '髟', strokes: 10, pinyin: 'biāo', definition: 'hair' },
  { num: 191, radical: '鬥', strokes: 10, pinyin: 'dòu', definition: 'fight' },
  {
    num: 192,
    radical: '鬯',
    strokes: 10,
    pinyin: 'chàng',
    definition: 'sacrificial wine',
  },
  {
    num: 193,
    radical: '鬲',
    strokes: 10,
    pinyin: 'lì',
    definition: 'cauldron',
  },
  { num: 194, radical: '鬼', strokes: 10, pinyin: 'guǐ', definition: 'ghost' },
  {
    num: 195,
    radical: '魚 (鱼)',
    strokes: 11,
    pinyin: 'yú',
    definition: 'fish',
  },
  {
    num: 196,
    radical: '鳥 (鸟)',
    strokes: 11,
    pinyin: 'niǎo',
    definition: 'bird',
  },
  {
    num: 197,
    radical: '卤 (鹵)',
    strokes: 7,
    pinyin: 'lǔ',
    definition: 'salt',
  },
  { num: 198, radical: '鹿', strokes: 11, pinyin: 'lù', definition: 'deer' },
  {
    num: 199,
    radical: '麥 (麦)',
    strokes: 11,
    pinyin: 'mài',
    definition: 'wheat',
  },
  { num: 200, radical: '麻', strokes: 11, pinyin: 'má', definition: 'hemp' },
  {
    num: 201,
    radical: '黃 (黄)',
    strokes: 12,
    pinyin: 'huáng',
    definition: 'yellow',
  },
  { num: 202, radical: '黍', strokes: 12, pinyin: 'shǔ', definition: 'millet' },
  { num: 203, radical: '黑', strokes: 12, pinyin: 'hēi', definition: 'black' },
  {
    num: 204,
    radical: '黹',
    strokes: 12,
    pinyin: 'zhǐ',
    definition: 'embroider',
  },
  {
    num: 205,
    radical: '黽 (黾)',
    strokes: 13,
    pinyin: 'mǐn',
    definition: 'frog',
  },
  {
    num: 206,
    radical: '鼎',
    strokes: 13,
    pinyin: 'dǐng',
    definition: 'tripod',
  },
  {
    num: 207,
    radical: '鼓 (鼔)',
    strokes: 13,
    pinyin: 'gǔ',
    definition: 'drum',
  },
  { num: 208, radical: '鼠', strokes: 13, pinyin: 'shǔ', definition: 'rat' },
  { num: 209, radical: '鼻', strokes: 14, pinyin: 'bí', definition: 'nose' },
  {
    num: 210,
    radical: '齊 (齐)',
    strokes: 14,
    pinyin: 'qí',
    definition: 'neat',
  },
  {
    num: 211,
    radical: '齒 (齿)',
    strokes: 15,
    pinyin: 'chǐ',
    definition: 'teeth',
  },
  {
    num: 212,
    radical: '龍 (龙)',
    strokes: 16,
    pinyin: 'lóng',
    definition: 'dragon',
  },
  {
    num: 213,
    radical: '龜 (龟)',
    strokes: 16,
    pinyin: 'guī',
    definition: 'turtle',
  },
  { num: 214, radical: '龠', strokes: 17, pinyin: 'yuè', definition: 'flute' },
];

function parseRadical(radicalStr: string): {
  char: string;
  variant: string;
} {
  const match = radicalStr.match(/^(\S+)\s*(?:\(([^)]+)\))?$/);
  if (!match) {
    return { char: radicalStr, variant: '' };
  }
  return {
    char: match[1],
    variant: match[2] || '',
  };
}

async function importRadicals() {
  console.log(`\n⟳ Importing 214 Kangxi radicals...\n`);

  const data = radicals.map((r) => {
    const { char, variant } = parseRadical(r.radical);
    return {
      id: `rad_${r.num.toString().padStart(3, '0')}`,
      char,
      variant,
      strokeCount: r.strokes,
      meaning: {
        pinyin: r.pinyin,
        en: r.definition,
      },
      frequency: r.num, // Lower numbers = more common
      imageUrl: null,
    };
  });

  try {
    const result = await prisma.radical.createMany({
      data,
      skipDuplicates: true,
    });

    console.log(`✓ Imported ${result.count} radicals`);

    // Get total count
    const total = await prisma.radical.count();
    console.log(`ℹ Total radicals in database: ${total}`);
  } catch (error) {
    console.error('✗ Error importing radicals:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

// Run import when executed directly
if (require.main === module) {
  importRadicals()
    .then(() => {
      console.log('\n✓ Import completed successfully\n');
      process.exit(0);
    })
    .catch((error) => {
      console.error('\n✗ Import failed:', error);
      process.exit(1);
    });
}

export { importRadicals };
